### ISSUE TITLE
Questionable GUI decisions

### ISSUE THREAD

**Issue by eric-unc** [COMP523TeamD/HeadCircumferenceTool#11]
![image](https://user-images.githubusercontent.com/54514192/226445557-109638c1-df8e-4de1-8f23-4e0867fde12f.png)

Window is too tall on my laptop per default. And I cannot read the text very well.

**Comment by jesse-wei** [comment]
The window is resizable but we can change the default width and height in src/GUI/main.py. (TODO: these variables should be put in settings.py).

GUI elements are disabled before opening image(s), which is why the text shows up like that. However, it shouldn't be that invisible even when disabled. Shows up fine on my laptop.

Check [https://github.com/COMP523TeamD/BreezeStyleSheets](https://github.com/COMP523TeamD/BreezeStyleSheets) (this is a link to our fork) for a JSON field that determines the color of disabled GUI elements, if it exists. Instructions for using exporting from BSS to the HCT repo are [here](https://headcircumferencetool.readthedocs.io/en/latest/dependencies.html#breezestylesheets), if you want to test it in our GUI.

I'm finishing up a few small changes FYI so will commit in a few.

**Comment by jesse-wei** [comment]
This is solved. But still need to fix the aspect ratio of the image or something similar.
