### ISSUE TITLE
How to run GUI?

### ISSUE THREAD

**Issue by mlouielu** [COMP523TeamD/HeadCircumferenceTool#4]

**Comment by jesse-wei** [comment]
`python -m src.GUI.main`

I'm going to commit to the `np_array` branch in just a moment so make sure to pull.

**Comment by jesse-wei** [comment]
Commited.

**Comment by jesse-wei** [comment]
Yeah, numpy array only seems to be very fast compared to saving JPG to disk.

The problem with numpy array only is that the files in ExampleData/, when converted to `sitk.Image` then `np` array, have data type `int16`, signed. The file at the top is actually `float32`.

Then we need to do numpy array -> QImage, and QImage expects Format_Grayscale8 or Format_Grayscale16 (pretty sure it's unsigned).

What's weird is even though every file except one are `int16`, when I check the values in the `np` array, the minimum is always 0, and the max is never anywhere near $2^{16}-1=65535$. Usually it's somewhere 500-1000. One file seems to have a maximum of 255, so that seems like `uint8`.

So the type conversion is somewhat tricky.

On the other hand, saving to JPG avoids any type conversion issues, and the images always look fine.

We'll probably have to reimplement whatever's going on in the JPG library if continuing with the `np` array approach (which is preferable).

**Comment by styner** [comment]
MRI data is commonly unsigned short/int16 as they come off the scanner, but preprocessing steps can result for them to be converted to float32 or float64/double. One way around that is to detect the presence of float data and inform the user of a predefined scaling, e.g. min..max to 0...10,000 (this could be user defined in the preferences/settings). This way, you can load the float data, map it to 0....10,000 and then cast it to int16

**Comment by jesse-wei** [comment]
> MRI data is commonly unsigned short/int16 as they come off the scanner, but preprocessing steps can result for them to be converted to float32 or float64/double (or int16 using full range to 64k). One way around that is to detect the presence of float data and inform the user of a predefined scaling, e.g. min..max to 0...10,000 (this could be user defined in the preferences/settings). This way, you can load the float data, map it to 0....10,000 and then cast it to int16

[qimage2ndarray](http://hmeine.github.io/qimage2ndarray/#converting-ndarrays-into-qimages) handles this problem, at least for rendering in the GUI.

Specifically, we're using the [gray2qimage](http://hmeine.github.io/qimage2ndarray/#qimage2ndarray.gray2qimage) function. Values are normalized to 0...255, which loses information since the source data usually lies in a larger range, but it's fine for image rendering to the user.

Could instead modify the source code to normalize to 0...65535 and use 8 bit grayscale if preferable.
